{{- if .Values.postgresDedicatedStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "postgresql.fullname" . }}-storage
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if (eq .Values.provider "gke") }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ template "fullname" . }}-fast
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresStorageSize }}
{{- end }}
